Dev2
KelliYots/Besit_Sprint_3 pull request #4
Opened 2021-12-15 10:07 UTC by KelliYots

Stas - top № 1!

2021-12-15 11:11 UTC, egorvas requested changes

2021-12-15 11:11 UTC, egorvas commented on .gitignore
> +/target/classes/
Можно было в игнор добавить все папку target
А папку с отчетом исключить из игнора через !

2021-12-15 11:11 UTC, egorvas commented on src/test/java/LoginCourierNegativeTest.java
> +public class LoginCourierNegativeTest {
У тебя по-прежнему нет теста, который находит проблему, которая вешает наш сервер. Это очень важно.

2021-12-15 11:46 UTC, KelliYots commented on src/test/java/LoginCourierNegativeTest.java
> +public class LoginCourierNegativeTest {
Ты говоришь о тесте courierCanBeLoginWithNoLogin
Чем он тебя не устраивает? Он не отвечает привычным образом, он виснет, я не понимаю что ещё ты хочешь тут увидеть

2021-12-16 07:00 UTC, KelliYots commented on src/test/java/LoginCourierNegativeTest.java
> +public class LoginCourierNegativeTest {
> У тебя по-прежнему нет теста, который находит проблему, которая вешает наш сервер. Это очень важно.

Ты говоришь о тесте courierCanBeLoginWithNoLogin
Чем он тебя не устраивает? Он не отвечает привычным образом, он виснет, я не понимаю что ещё ты хочешь тут увидеть

2022-01-28 23:56 UTC, merged